import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';
import Header from "@/components/layout/header";

import { DM_Sans } from 'next/font/google';

const dmSans = DM_Sans({
  variable: '--font-dm-sans',
  subsets: ['latin'],
  weight: ['400','500', '600', '700', '800', '900'],
  style: ['normal'],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={dmSans.variable}>
        <Header />
        {children}
      </body>
    </html>
  );
}
